- name: Install and configure MariaDB
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install unzip, mariadb, and mariadb-server
      apt:
        name:
          - unzip
          - mariadb-server
        state: present

    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes