- hosts: all
  become: yes
  tasks:
    - name: Copy files from Homework4 folder to remote machine
      ansible.builtin.copy:
        src: ./main.yml
        dest: /nde
        owner: tim
        group: devops
        mode: '0755'

    - name: Copy files from Homework4 folder to remote machine
      ansible.builtin.copy:
        src: ./hosts
        dest: /nde
        owner: tim
        group: devops
        mode: '0755'  